services:
  postgres:
    image: postgres:latest
    container_name: chat_app-db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: chat_app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
